# Generated by Django 4.2 on 2023-12-06 11:29

import ckeditor.fields
import courses.services
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('name_uz', models.CharField(max_length=250, null=True)),
                ('name_ru', models.CharField(max_length=250, null=True)),
                ('name_en', models.CharField(max_length=250, null=True)),
                ('sub_name', models.CharField(max_length=250)),
                ('sub_name_uz', models.CharField(max_length=250, null=True)),
                ('sub_name_ru', models.CharField(max_length=250, null=True)),
                ('sub_name_en', models.CharField(max_length=250, null=True)),
                ('duration', models.CharField(max_length=50)),
                ('duration_uz', models.CharField(max_length=50, null=True)),
                ('duration_ru', models.CharField(max_length=50, null=True)),
                ('duration_en', models.CharField(max_length=50, null=True)),
                ('description', ckeditor.fields.RichTextField()),
                ('description_uz', ckeditor.fields.RichTextField(null=True)),
                ('description_ru', ckeditor.fields.RichTextField(null=True)),
                ('description_en', ckeditor.fields.RichTextField(null=True)),
                ('image', models.ImageField(upload_to=courses.services.upload_course_path)),
                ('amount', models.PositiveIntegerField()),
                ('is_online', models.BooleanField()),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='CourseApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=16)),
                ('work_place', models.CharField(max_length=150)),
                ('is_checked', models.BooleanField(blank=True, default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applications', to='courses.course')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applications', to='main.region')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
