# Generated by Django 4.2 on 2023-12-06 11:29

from django.db import migrations, models
import django.db.models.deletion
import onlineservices.services


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_number', models.CharField(blank=True, max_length=30, null=True)),
                ('contract_file', models.FileField(blank=True, null=True, upload_to=onlineservices.services.upload_contract_file_path)),
                ('contract_type', models.CharField(blank=True, max_length=250, null=True)),
                ('is_company', models.BooleanField(default=False)),
                ('organization', models.CharField(blank=True, max_length=150)),
                ('organization_director', models.CharField(blank=True, max_length=150)),
                ('payment_percent', models.CharField(max_length=5)),
                ('phone', models.CharField(blank=True, max_length=16, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_checked', models.BooleanField(blank=True, default=False)),
                ('is_confirmed', models.BooleanField(blank=True, default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('rek_org_name', models.CharField(blank=True, max_length=250, null=True)),
                ('rek_org_address', models.CharField(blank=True, max_length=250, null=True)),
                ('rek_org_bank', models.CharField(blank=True, max_length=30, null=True)),
                ('rek_org_hisob_raqam', models.CharField(blank=True, max_length=30, null=True)),
                ('rek_org_account_hisob_raqam', models.CharField(blank=True, max_length=30, null=True)),
                ('rek_org_mfo', models.CharField(blank=True, max_length=30, null=True)),
                ('rek_org_inn', models.CharField(blank=True, max_length=30, null=True)),
                ('rek_org_inn_gazna', models.CharField(blank=True, max_length=50, null=True)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contracts', to='main.region')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Faq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=250)),
                ('question_uz', models.CharField(max_length=250, null=True)),
                ('question_ru', models.CharField(max_length=250, null=True)),
                ('question_en', models.CharField(max_length=250, null=True)),
                ('answer', models.CharField(max_length=500)),
                ('answer_uz', models.CharField(max_length=500, null=True)),
                ('answer_ru', models.CharField(max_length=500, null=True)),
                ('answer_en', models.CharField(max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ContractUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('position', models.CharField(blank=True, max_length=150)),
                ('phone', models.CharField(max_length=16)),
                ('passport_data', models.CharField(max_length=10)),
                ('jshshir', models.CharField(max_length=14)),
                ('passport_file', models.FileField(blank=True, null=True, upload_to=onlineservices.services.upload_contract_user_path)),
                ('is_active', models.BooleanField(default=True)),
                ('is_checked', models.BooleanField(blank=True, default=False)),
                ('is_confirmed', models.BooleanField(blank=True, default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='users', to='onlineservices.contract')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
