# Generated by Django 4.2 on 2023-12-06 11:29

import competition.services
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompetetionCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.CharField(max_length=150)),
                ('body_uz', models.CharField(max_length=150, null=True)),
                ('body_ru', models.CharField(max_length=150, null=True)),
                ('body_en', models.CharField(max_length=150, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CompetetionQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('name_uz', models.CharField(max_length=150, null=True)),
                ('name_ru', models.CharField(max_length=150, null=True)),
                ('name_en', models.CharField(max_length=150, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('education', models.BooleanField(default=False)),
                ('experience', models.BooleanField(default=False)),
                ('specialty', models.BooleanField(default=False)),
                ('achievement', models.BooleanField(default=False)),
                ('qualification', models.BooleanField(default=False)),
                ('academ_experience', models.BooleanField(default=False)),
                ('seminar_participation', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('name_uz', models.CharField(max_length=150, null=True)),
                ('name_ru', models.CharField(max_length=150, null=True)),
                ('name_en', models.CharField(max_length=150, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CompetitionParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=16)),
                ('work_place', models.CharField(max_length=150)),
                ('is_active', models.BooleanField(default=True)),
                ('is_confirmed', models.BooleanField(default=False)),
                ('education_file', models.FileField(blank=True, null=True, upload_to=competition.services.upload_participant_path)),
                ('education_is_confirmed', models.BooleanField(blank=True, default=False)),
                ('education_ball', models.SmallIntegerField(blank=True, choices=[(0, 0), (2, 2), (5, 5), (10, 10)], default=0)),
                ('specialty_file', models.FileField(blank=True, null=True, upload_to=competition.services.upload_participant_path)),
                ('specialty_is_confirmed', models.BooleanField(blank=True, default=False)),
                ('specialty_ball', models.SmallIntegerField(blank=True, choices=[(0, 0), (6, 6), (8, 8), (10, 10)], default=0)),
                ('experience_file', models.FileField(blank=True, null=True, upload_to=competition.services.upload_participant_path)),
                ('experience_is_confirmed', models.BooleanField(blank=True, default=False)),
                ('experience_ball', models.SmallIntegerField(blank=True, choices=[(0, 0), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], default=0)),
                ('achievement_file', models.FileField(blank=True, null=True, upload_to=competition.services.upload_participant_path)),
                ('achievement_is_confirmed', models.BooleanField(blank=True, default=False)),
                ('achievement_ball', models.SmallIntegerField(blank=True, choices=[(0, 0), (2, 2), (3, 3), (5, 5), (7, 7), (10, 10)], default=0)),
                ('qualification_file', models.FileField(blank=True, null=True, upload_to=competition.services.upload_participant_path)),
                ('qualification_is_confirmed', models.BooleanField(blank=True, default=False)),
                ('qualification_ball', models.SmallIntegerField(blank=True, choices=[(0, 0), (5, 5), (8, 8), (10, 10)], default=0)),
                ('academ_experience_file', models.FileField(blank=True, null=True, upload_to=competition.services.upload_participant_path)),
                ('academ_experience_is_confirmed', models.BooleanField(blank=True, default=False)),
                ('academ_experience_ball', models.SmallIntegerField(blank=True, choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (6, 6), (10, 10), (14, 14), (18, 18)], default=0)),
                ('seminar_participation_file', models.FileField(blank=True, null=True, upload_to=competition.services.upload_participant_path)),
                ('seminar_participation_is_confirmed', models.BooleanField(blank=True, default=False)),
                ('seminar_participation_ball', models.SmallIntegerField(blank=True, choices=[(0, 0), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (10, 10)], default=0)),
                ('language_cert', models.CharField(blank=True, max_length=5, null=True)),
                ('language_cert_file', models.FileField(blank=True, null=True, upload_to=competition.services.upload_participant_path)),
                ('language_cert_is_confirmed', models.BooleanField(blank=True, default=False)),
                ('language_cert_ball', models.SmallIntegerField(blank=True, choices=[(0, 0), (7, 7), (10, 10), (14, 14), (18, 18)], default=0)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('academ_experience', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='academ_participants', to='competition.competetionquestion')),
                ('achievement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='achievement_participants', to='competition.competetionquestion')),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='competition.competition')),
                ('education', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='education_participants', to='competition.competetionquestion')),
                ('experience', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='experience_participants', to='competition.competetionquestion')),
                ('qualification', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='qualification_participants', to='competition.competetionquestion')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
