# Generated by Django 4.2 on 2023-12-06 11:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('competition', '0001_initial'),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='competitionparticipant',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='participants', to='main.region'),
        ),
        migrations.AddField(
            model_name='competitionparticipant',
            name='seminar_participation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='seminar_participants', to='competition.competetionquestion'),
        ),
        migrations.AddField(
            model_name='competitionparticipant',
            name='specialty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='specialty_participants', to='competition.competetionquestion'),
        ),
        migrations.AddField(
            model_name='competetioncondition',
            name='competition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conditions', to='competition.competition'),
        ),
    ]
