# Generated by Django 4.2 on 2023-12-06 11:29

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion
import main.services


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('competition', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CenterContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tel', models.CharField(max_length=16)),
                ('address', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='CenterInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('title_uz', models.CharField(max_length=150, null=True)),
                ('title_ru', models.CharField(max_length=150, null=True)),
                ('title_en', models.CharField(max_length=150, null=True)),
                ('subtitle', models.CharField(max_length=150)),
                ('subtitle_uz', models.CharField(max_length=150, null=True)),
                ('subtitle_ru', models.CharField(max_length=150, null=True)),
                ('subtitle_en', models.CharField(max_length=150, null=True)),
                ('body', models.TextField()),
                ('body_uz', models.TextField(null=True)),
                ('body_ru', models.TextField(null=True)),
                ('body_en', models.TextField(null=True)),
                ('file', models.FileField(upload_to=main.services.upload_center_info_path)),
                ('is_history', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='CenterStructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=main.services.upload_center_structure_path)),
                ('image_uz', models.ImageField(null=True, upload_to=main.services.upload_center_structure_path)),
                ('image_ru', models.ImageField(null=True, upload_to=main.services.upload_center_structure_path)),
                ('image_en', models.ImageField(null=True, upload_to=main.services.upload_center_structure_path)),
            ],
        ),
        migrations.CreateModel(
            name='DocumentCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('name_uz', models.CharField(max_length=150, null=True)),
                ('name_ru', models.CharField(max_length=150, null=True)),
                ('name_en', models.CharField(max_length=150, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('name_uz', models.CharField(max_length=250, null=True)),
                ('name_ru', models.CharField(max_length=250, null=True)),
                ('name_en', models.CharField(max_length=250, null=True)),
                ('description', models.TextField()),
                ('description_uz', models.TextField(null=True)),
                ('description_ru', models.TextField(null=True)),
                ('description_en', models.TextField(null=True)),
                ('image', models.ImageField(upload_to=main.services.upload_gallery_path)),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='LeaderAndTrener',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50)),
                ('full_name_uz', models.CharField(max_length=50, null=True)),
                ('full_name_ru', models.CharField(max_length=50, null=True)),
                ('full_name_en', models.CharField(max_length=50, null=True)),
                ('about', models.CharField(max_length=70)),
                ('about_uz', models.CharField(max_length=70, null=True)),
                ('about_ru', models.CharField(max_length=70, null=True)),
                ('about_en', models.CharField(max_length=70, null=True)),
                ('image', models.ImageField(upload_to=main.services.upload_leader_trener_path)),
                ('is_leader', models.BooleanField(default=True)),
                ('work_time', models.CharField(blank=True, max_length=15)),
                ('phone', models.CharField(blank=True, max_length=16)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('telegram', models.URLField(blank=True, null=True)),
                ('instagram', models.URLField(blank=True, null=True)),
                ('facebook', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('name_uz', models.CharField(max_length=150, null=True)),
                ('name_ru', models.CharField(max_length=150, null=True)),
                ('name_en', models.CharField(max_length=150, null=True)),
                ('description', models.TextField()),
                ('description_uz', models.TextField(null=True)),
                ('description_ru', models.TextField(null=True)),
                ('description_en', models.TextField(null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_news', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150, null=True)),
                ('logo', models.ImageField(upload_to=main.services.upload_partner_path)),
                ('url', models.URLField()),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('name_uz', models.CharField(max_length=40, null=True)),
                ('name_ru', models.CharField(max_length=40, null=True)),
                ('name_en', models.CharField(max_length=40, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('online', models.PositiveIntegerField()),
                ('offline', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('title_uz', models.CharField(max_length=150, null=True)),
                ('title_ru', models.CharField(max_length=150, null=True)),
                ('title_en', models.CharField(max_length=150, null=True)),
                ('image', models.ImageField(upload_to=main.services.upload_slider_path)),
                ('url', models.URLField()),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='UserContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('phone', models.CharField(blank=True, max_length=16)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('academic_degree', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_contacts', to='competition.competetionquestion')),
            ],
        ),
        migrations.CreateModel(
            name='EventImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=main.services.upload_gallery_path)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='images', to='main.event')),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('name_uz', models.CharField(max_length=150, null=True)),
                ('name_ru', models.CharField(max_length=150, null=True)),
                ('name_en', models.CharField(max_length=150, null=True)),
                ('file', models.FileField(upload_to=main.services.upload_document_path)),
                ('file_uz', models.FileField(null=True, upload_to=main.services.upload_document_path)),
                ('file_ru', models.FileField(null=True, upload_to=main.services.upload_document_path)),
                ('file_en', models.FileField(null=True, upload_to=main.services.upload_document_path)),
                ('url', models.URLField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='files', to='main.documentcategory')),
            ],
        ),
        migrations.CreateModel(
            name='CenterSocial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('code', models.CharField(max_length=20)),
                ('url', models.URLField()),
                ('center', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='socials', to='main.centercontact')),
            ],
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('name_uz', models.CharField(max_length=150, null=True)),
                ('name_ru', models.CharField(max_length=150, null=True)),
                ('name_en', models.CharField(max_length=150, null=True)),
                ('about', models.TextField()),
                ('about_uz', models.TextField(null=True)),
                ('about_ru', models.TextField(null=True)),
                ('about_en', models.TextField(null=True)),
                ('description', ckeditor.fields.RichTextField()),
                ('description_uz', ckeditor.fields.RichTextField(null=True)),
                ('description_ru', ckeditor.fields.RichTextField(null=True)),
                ('description_en', ckeditor.fields.RichTextField(null=True)),
                ('image', models.ImageField(upload_to=main.services.upload_branch_path)),
                ('site', models.URLField()),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='branches', to='main.region')),
            ],
        ),
    ]
